// const { chromium } = require("@playwright/test");
// (async()=>{
//   const browser = await chromium.launch({ headless: true });
//   const page = await browser.newPage({ baseURL: "https://parabank.parasoft.com" });
//   await page.goto('/parabank/index.htm');
//   await page.fill('input[name="username"]', 'john');
//   await page.fill('input[name="password"]', 'demo');
//   await page.click('input[type="submit"][value="Log In"]');
//   await page.waitForURL('**/overview.htm', { timeout: 10000 });
//   await page.click('a:has-text("Open New Account")');
//   await page.waitForURL('**/openaccount.htm', { timeout: 10000 });
//   await page.waitForSelector('input[value="Open New Account"]', { state: 'visible', timeout: 10000 });
//   await page.selectOption('#type', '0');
//   await page.selectOption('#fromAccountId', '12345');
//   await page.click('input[value="Open New Account"]');
//   await page.waitForTimeout(3000);
//   const url = page.url();
//   const title = await page.title();
//   const body = await page.innerText('body');
//   const h1s = await page.$$eval('h1', els => els.map(e => ({text: e.textContent?.trim(), hidden: e.hidden, display: window.getComputedStyle(e).display, visibility: window.getComputedStyle(e).visibility, opacity: window.getComputedStyle(e).opacity, rect: e.getBoundingClientRect().toJSON()})));
//   const resultLinks = await page.$$eval('p a', els => els.map(e => ({text: e.textContent?.trim(), href: e.getAttribute('href')})));
//   console.log('URL:', url);
//   console.log('TITLE:', title);
//   console.log('H1s:', JSON.stringify(h1s,null,2));
//   console.log('P A:', JSON.stringify(resultLinks,null,2));
//   console.log('BODY-first-400:', body.slice(0,400).replace(/\n/g,' '));
//   await browser.close();
// })();
